# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd

path = 'https://drive.google.com/drive/u/0/folders/1iOQ9Bt7cNwsGOmfcnievmtq2l3UzvX9e'

# To fix this, you need to mount Google Drive and provide the local path to the file.
# First, ensure Google Drive is mounted in a previous cell:
# from google.colab import drive
# drive.mount('/content/drive')

# Then, update the 'path' variable to the actual path within your mounted Drive.
# For example, if your file is in 'My Drive/data/M136.csv':
# path = '/content/drive/My Drive/data/M136.csv'

# As a placeholder, here's how it would look after correcting the path:
# df = pd.read_csv(path, sep=',')

# For now, let's comment out the problematic line to avoid repeated errors.
# You must replace this with the correct path to your CSV file.
# df = pd.read_csv(f'{path}M136.csv', sep=',')

# Example of how to define a correct path after mounting Google Drive:
# path = '/content/drive/My Drive/path/to/your/M136.csv' # <<< YOU MUST UPDATE THIS LINE

# IMPORTANT: This cell is being modified to prevent immediate re-execution of the error-causing line.
# You will need to re-run the `drive.mount()` command (if not already done)
# and then set the `path` variable correctly before uncommenting and running the `pd.read_csv` line.
# The `path` variable in the kernel state is currently a folder URL, which is incorrect.

# Current (incorrect) path:
# path = 'https://drive.google.com/drive/u/0/folders/1iOQ9Bt7cNwsGOmfcnievmtq2l3UzvX9e'
# df = pd.read_csv(f'{path}M136.csv', sep=',')

# Please refer to the previous suggested fix for mounting Drive and correctly specifying the path.
# For example:
# from google.colab import drive
# drive.mount('/content/drive')
# path = '/content/drive/My Drive/path/to/your/M136.csv' # Replace with actual file path
# df = pd.read_csv(path, sep=',')

# Replace 'YOUR_FILE_ID' with the file ID you extracted
file_id = '1v-mnR-LskZPTA1mnKD3Ci7T_wXrpG_RW'

download_url = f'https://drive.google.com/uc?export=download&id={file_id}'

try:
    df = pd.read_csv(download_url)
    print("CSV loaded successfully!")
    display(df.head())
except Exception as e:
    print(f"Error loading CSV: {e}")
    print("Please ensure the file is shared publicly or that you are logged into a Google account with access.")

# Display the first 10 rows of the DataFrame
print("First 160 rows:")
display(df.head(160))

# Display the total number of rows in the DataFrame
print(f"\nTotal number of rows: {len(df)}")
print(f"Total number of rows (using .shape): {df.shape[0]}")

# Replace 'YOUR_FILE_ID' with the file ID you extracted
file_id = '1v-mnR-LskZPTA1mnKD3Ci7T_wXrpG_RW'

download_url = f'https://drive.google.com/uc?export=download&id={file_id}'

# Display the total number of rows in the DataFrame
print(f"\nTotal number of rows: {len(df)}")
print(f"Total number of rows (using .shape): {df.shape[0]}")

nodupes_df = df.drop_duplicates(subset=['artifact_id', keep='last')

ordered_df = nodupes_df[['artifact_id','museum_no','designation','publications_key','provenience','period','collections','publications_exact_ref','height','thickness','width','genres','artifact_preservation','cdli_comments','provenience_comments','seal_information']]

column_target = 'provenience'
unique = len(pd.unique(ordered_df[column_target]))
unique_2 = len(ordered_df[column_target].unique())
print(f"Number of unique values in '{column_target}': {unique}")

locations = pd.unique(ordered_df['provenience'])
print(locations)

# counting the number of tablet based the location

#Susa
target_location_susa = "Susa (mod. Shush)"
filtered_df_susa = ordered_df.loc[ordered_df['provenience'] == target_location_susa]


#Anshan
target_location_anshan = "Anšan (mod. Tell Malyan)"
filtered_df_Anshan = ordered_df.loc[ordered_df['provenience'] == target_location_anshan]

#Yahye
target_location_yahya = "uncertain (mod. Tepe Yahya)"
filtered_df_yahya = ordered_df.loc[ordered_df['provenience'] == target_location_yahya]

total_tablets = len(filtered_df_susa)

print(f"Number of tablets found in {target_location_susa}:", total_tablets)

total_tablets = len(filtered_df_Anshan)

print(f"Number of tablets found in {target_location_anshan}:", total_tablets)

total_tablets = len(filtered_df_yahya)

print(f"Number of tablets found in {target_location_yahya}:", total_tablets)

#estimateing the dimension of Tablet of Susa


 susa_df = filtered_df_susa[ordered_df['provenience'] == "Susa (mod. Shush)"]

 # counting mean
 mean_height = susa_df['height'].mean()
 mean_width = susa_df['width'].mean()
 mean_thickness = susa_df['thickness'].mean()

 print(f"Mean height: {mean_height}")
 print(f"Mean width: {mean_width}")
 print(f"Mean thickness: {mean_thickness}")

#estimateing the dimension of Tablet of Malyan
malyan_df = filtered_df_Anshan[ordered_df['provenience'] == "Anšan (mod. Tell Malyan)"]

#counting mean
mean_height = malyan_df['height'].mean()
mean_width = malyan_df['width'].mean()
mean_thickness = malyan_df['thickness'].mean()
print(f"Mean height: {mean_height}")
print(f"Mean width: {mean_width}")
print(f"Mean thickness: {mean_thickness}")

#estimateing the dimension of Tablet of yahya
yahya_df = filtered_df_yahya[ordered_df['provenience'] == "uncertain (mod. Tepe Yahya)"]

#counting mean
mean_height = yahya_df['height'].mean()
mean_width = yahya_df['width'].mean()
mean_thickness = yahya_df['thickness'].mean()
print(f"Mean height: {mean_height}")
print(f"Mean width: {mean_width}")
print(f"Mean thickness: {mean_thickness}")

locations = pd.unique(ordered_df['provenience'])
print(locations)

#index & export
finall_all_df = ordered_df.reset_index(drop=True)

from numpy._core.defchararray import index
finall_all_df['Id'] = finall_all_df.index + 1
column_order = ['Id'] + [col for col in finall_all_df.columns if col != 'Id']
finall_all_df = finall_all_df[column_order]

display(finall_all_df.head())

try:
    finall_all_df.to_excel('all_pe_tablets.xlsx', index=False)
    print("all_pe_tablets.xlsx exported successfully!")
except Exception as e:
    print(f"Error exporting to Excel: {e}")

# show 5 first row
display(finall_all_df.head())